CMP = g++
CLASS = bottleDate
MAIN = testDate
EXEC = test

$(EXEC): $(CLASS).o $(MAIN).o
	$(CMP) $(CLASS).o $(MAIN).o -o $(EXEC) -std=c++11

$(CLASS).o: $(CLASS).cpp $(CLASS).h
	$(CMP) -c $(CLASS).cpp -o $(CLASS).o -std=c++11

$(MAIN).o: $(MAIN).cpp $(CLASS).h 
	$(CMP) -c $(MAIN).cpp -o $(MAIN).o -std=c++11

clean:
	rm *.o
	rm $(EXEC)
